PROJECT = asteroids
DEPS = lager cowboy jiffy
ERLC_OPTS := +'{parse_transform, lager_transform}'
dep_lager = git https://github.com/basho/lager master
dep_cowboy = git https://github.com/ninenines/cowboy master
dep_jiffy = git https://github.com/davisp/jiffy.git master
include erlang.mk